---
driver:
  name: docker
  privileged: true

provisioner:
  name: ansible_playbook
  hosts: test-kitchen
  requirements_path: requirements.yml

platforms:
  - name: ubuntu-14.04
suites:
  - name: default
