---
sudo: required

services: docker

install:
- bundle install

script:
- kitchen test

notifications:
  slack:
    secure: du9zKH9K3VXr6DwxQ50xbqIAFlPFfOCI4VYQ7HdlRrkbapInRB4R7Uh6KcE7wCy4LUPZE4B2Siqu4n7XRZoPks6zUa64sfY8maNi29Omn7FKoLl0Dv+nVJTYCzWG+W0B1BBQjjUUAkGgcy4pWZiZ/xuAaAG/cWN9FzFF8iP7IXOnQ3tEGkyk6m7ts2YoyegSAm1BKUpAveq3+N5TpMD/j/6VLKnTRXgZ9VCRXao+uvI0kFEF7hQf/VslpdzAEAzphAsIGRuM605j7sFnlkvyCz39Qd4bnUQ4jjHVDLb01+fB2dkXtUBhBrZnbvGMzJrJY+B0jmJwyacGLTSBI3VrPQkiIXp+/t9sNn6hwJFokcncr1kLcIHh9NZ1kSkZiKHiXLmj7qU7iDueJ874AWklaaRAr9MegEaP+mNz5lprMlMN1KLXcSeEnwyDVkdOdkiRrPZl+81XoQaanSj9DczV50Y3TDRQSU/gOZlztMghN7arH/Tk5FDdgCYtAybP3VcUD2XroZOOPBOkM5qmyhzu28a/027KsO/FzWqicUhaSUY2XafSJf0WojpEd5stdJU2iaGxRaSHwPemZ408K3J8nDdUiR4BM+cIY8PvpSJuLNp16WzWm0dMwAUOdwU61XiFu3MMe05E5jX2+K3p9YOWST1mnOpeNkUCWNVIaYcEDAE=
