---
- name: "Directory Exists | {{ influxdb_runtime_root }} "
  file:
    state: directory
    path: "{{ influxdb_runtime_root }}"
    owner: "{{ infludxb_user }}"
    group: "{{ influxdb_group }}"
    mode: 0775
    notify: service | influxdb | stopped
  tags:
    - directory-structure
    - runtime-data
