---
- name: Configure | InfluxDB
  lineinfile:
    state: present
    dest: /etc/mongod.conf
    regexp: '^#* *auth ?\='
    line: 'auth = true'
  when: mongodb_auth_enabled
  notify: Reload Service | influxdb
  tags:
    - configuration
    - precise-configuration
    - influxdb

- name: Configure | InfluxDB  
  lineinfile:
    state: absent
    dest: /etc/mongod.conf
    regexp: '^#* *bind_ip'
  when: mongodb_accepts_external_connections
  notify: Reload Service | influxdb
  tags:
    - configuration
    - precise-configuration
    - influxdb
